name: GitHub Actions Demo 3
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
      - uses: actions/checkout@v3
      - run: curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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