name: GitHub Actions Demo 3
on: [push]
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Slack Notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}